
services:
  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRESQL_DB=task_manager_db
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
  api:
    build: .
    container_name: task_manager_api
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    depends_on:
      - db